image: php:7.3

#cache:
#  key: ${CI_COMMIT_REF_SLUG}
#  paths:
#    - vendor/

stages:
  #  - test
  - deploy

before_script:
  - apt-get update
  - apt-get install -y libzip-dev openssh-client rsync
  - docker-php-ext-install zip
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - ssh-keyscan "$DEV_WIKI_URL" >> ~/.ssh/known_hosts
  - ssh-keyscan "$DEV_PHPDOC_URL" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - wget https://pear.phpdoc.org/channel.xml
  - pear channel-add ./channel.xml
  - pear install https://pear.phpdoc.org/get/phpDocumentor-2.9.0.tgz
  - php composer.phar install

#test:
#  stage: test
#  script:
#    - ./vendor/bin/codecept run

deploy_wiki_develop:
  stage: deploy
  script:
    - echo "Compile the wiki for develop branch."
    - ./vendor/bin/bookdown src/wiki/bookdown.json
    - rsync -rvI --delete --exclude=".*" "/wiki/" "$DEV_DEPLOYER"@"$DEV_WIKI_URL":"$DEV_WIKI_PATH/"
    - ssh "$DEV_DEPLOYER"@"$DEV_WIKI_URL" "sudo chown -R $DEV_DEPLOYER:www-data $DEV_WIKI_PATH/*"
  only:
    - develop

deploy_phpdoc_develop:
  stage: deploy
  script:
    - echo "Deploy the phpdoc for develop branch."
    - phpdoc run
    - rsync -rvI --delete --exclude=".*" "public/phpdoc/" "$DEV_DEPLOYER"@"$DEV_PHPDOC_URL":"$DEV_PHPDOC_PATH/"
    - ssh "$DEV_DEPLOYER"@"$DEV_PHPDOC_URL" "sudo chown -R $DEV_DEPLOYER:www-data $DEV_PHPDOC_PATH/*"
  only:
    - develop

#deploy_wiki_master:
#  stage: deploy
#  script:
#    - rsync -rvI --delete --exclude=".*" "/wiki/" "$PROD_DEPLOYER"@"$PROD_WIKI_URL":"$PROD_WIKI_PATH/"
#    - ssh "$PROD_DEPLOYER"@"$PROD_WIKI_URL" "sudo chown -R $PROD_DEPLOYER:www-data $WIKI_PATH/*"
#  only:
#    - master

#deploy_phpdoc_master:
#  stage: deploy
#  script:
#    - rsync -rvI --delete --exclude=".*" "/phpdoc/" "$PROD_DEPLOYER"@"$PROD_PHPDOC_URL":"$PROD_PHPDOC_PATH/"
#    - ssh "$PROD_DEPLOYER"@"$PROD_PHPDOC_URL" "sudo chown -R $PROD_DEPLOYER:www-data $PROD_PHPDOC_PATH/*"
#  only:
#    - master
