# GitLab pipelines definition.
# @author john89 (https://gitlab.com/john89)
# @copyright 2020-2030 GaterData
# @license This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
#     If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
# @link https://gaterdata.com

image: php:7.3

#before_script:
#  - apt-get update
#  - apt-get install -y libzip-dev openssh-client rsync libxslt-dev
#  - docker-php-ext-install zip xsl
#  - eval $(ssh-agent -s)
#  - mkdir -p ~/.ssh
#  - chmod 700 ~/.ssh
#  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
#  - php composer-setup.php
#  - php -r "unlink('composer-setup.php');"
#  - php composer.phar install

#cache:
#  key: "$CI_COMMIT_REF_SLUG"
#  paths:
#    - vendor/

stages:
  - lint
  - test
  - build
  - deploy

#phpcs:
#  stage: lint
#  script:
#    - ./vendor/bin/phpcs --standard=gaterdata_phpcs_rulesset.xml includes/ src/scss/ src/js/

#funtional_tests:
#  stage: test
#  script:
#    - ./vendor/bin/codecept run

#unit_tests:
#  stage: test

#deploy_wiki_develop:
#  stage: deploy
#  only:
#    - develop
#  script:
#    - echo "Compile the wiki for develop branch."
#    - ssh-keyscan "$DEV_WIKI_URL" >> ~/.ssh/known_hosts
#    - chmod 644 ~/.ssh/known_hosts
#    - ./vendor/bin/bookdown src/wiki/bookdown.json
#    - rsync -rvI --delete --exclude=".*" "/wiki/" "$DEV_DEPLOYER"@"$DEV_WIKI_URL":"$DEV_WIKI_PATH/"
#    - rsync -rvI "$CI_PROJECT_DIR/src/wiki/images" "$DEV_DEPLOYER"@"$DEV_WIKI_URL":"$DEV_WIKI_PATH/"
#    - ssh "$DEV_DEPLOYER"@"$DEV_WIKI_URL" "sudo chown -R $DEV_DEPLOYER:www-data $DEV_WIKI_PATH/*"

build_phpdoc:
  image: phpdoc/phpdoc
  stage: build
  only:
    - develop
  artifacts:
    paths:
      - public/phpdoc
  script:
    - echo "Compile the phpdoc."
    - bundle run

#build_bookdown:
#  image: phpdoc/phpdoc
#  stage: build
#  only: develop
#  artifacts:
#    paths:
#      - build/
#  script:
#    - echo "Compile the wiki."

#deploy_phpdoc_develop:
#  stage: deploy
#  only:
#    - develop
#  dependencies:
#    - build_phpdoc
#  script:
#    - echo "Deploy the phpdoc for develop branch."
#    - rsync -rvI --delete --exclude=".*" "./build/public/phpdoc/" "$DEV_DEPLOYER"@"$DEV_PHPDOC_URL":"$DEV_PHPDOC_PATH/"
#    - ssh "$DEV_DEPLOYER"@"$DEV_PHPDOC_URL" "sudo chown -R $DEV_DEPLOYER:www-data $DEV_PHPDOC_PATH/*"

#deploy_wiki_master:
#  stage: deploy
#  script:
#    - rsync -rvI --delete --exclude=".*" "/wiki/" "$PROD_DEPLOYER"@"$PROD_WIKI_URL":"$PROD_WIKI_PATH/"
#    - ssh "$PROD_DEPLOYER"@"$PROD_WIKI_URL" "sudo chown -R $PROD_DEPLOYER:www-data $WIKI_PATH/*"
#  only:
#    - master

#deploy_phpdoc_master:
#  stage: deploy
#  script:
#    - rsync -rvI --delete --exclude=".*" "/phpdoc/" "$PROD_DEPLOYER"@"$PROD_PHPDOC_URL":"$PROD_PHPDOC_PATH/"
#    - ssh "$PROD_DEPLOYER"@"$PROD_PHPDOC_URL" "sudo chown -R $PROD_DEPLOYER:www-data $PROD_PHPDOC_PATH/*"
#  only:
#    - master
