version: '3.7'

services:

  admin:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - "./docker/nginx/admin.conf:/etc/nginx/conf.d/default.conf"
      - ".:/usr/share/nginx/html"
    networks:
      - api_network
    container_name: "${APP_NAME}-admin"
    
  php:
    build: ./docker/php
    image: php:fpm
    ports:
      - "9000:9000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ".:/var/www/html"
    networks:
      - api_network
    container_name: "${APP_NAME}-php"

  db:
    image: mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - api_network
    container_name: "${APP_NAME}-db"
    volumes:
      - ./dbdata:/var/lib/mysql

networks:
  api_network:
    driver: bridge