version: '3.7'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: "${APP_NAME}-proxy"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - api_network

  api:
    image: nginx
    container_name: "${APP_NAME}-api"
    ports:
      - 80
    volumes:
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}:/var/www/html
    environment:
      - VIRTUAL_HOST=${API_DOMAIN}
    depends_on:
      - php
    networks:
      api_network:
        aliases:
          - ${API_DOMAIN}

  admin:
    image: nginx
    container_name: "${APP_NAME}-admin"
    ports:
      - 80
    volumes:
      - ./docker/nginx/admin.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}:/var/www/html
    environment:
      - VIRTUAL_HOST=${ADMIN_DOMAIN}
    depends_on:
      - php
    networks:
      api_network:
        aliases:
          - ${ADMIN_DOMAIN}
    
  php:
    image: php:fpm
    container_name: "${APP_NAME}-php"
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./composer:/composer
      - .:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - api_network
  
  composer:
    image: composer
    container_name: "${APP_NAME}-composer"
    ports:
      - "9001:9000"
    volumes:
      - .:/app
    command: install
    networks:
      - api_network

  db:
    image: mariadb
    container_name: "${APP_NAME}-db"
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    networks:
      - api_network

networks:
  api_network:
    driver: bridge