version: '2'

services:

  gaterdata-admin:
    image: nginx:latest
    container_name: gaterdata-admin
    environment:
      - VIRTUAL_HOST=admin.gaterdata.local
      - VIRTUAL_PORT=80
    volumes:
      - .:/var/www/html
      - .docker/vhost.d/admin.gaterdata.conf:/etc/nginx/vhost.d/admin.gaterdata.local:ro
    links:
      - php

  # gaterdata-api:
  #   image: nginx:latest
  #   container_name: gaterdata-api
  #   environment:
  #     VIRTUAL_HOST: ${GATERDATA_API}
  #     VIRTUAL_PORT: 80
  #   volumes:
  #     - .:/var/www/html
  #     - .docker/vhost.d/api.gaterdata.conf:/etc/nginx/vhost.d/${GATERDATA_API}:ro
  #   links:
  #     - php
      
  php:
    image: php:7-fpm
    container_name: gaterdata-php
    volumes:
      - .:/var/www/html

# networks:
#   default:
#     external:
#       name: nginx-proxy