version: '3.4'

services:
  
  proxy:
    container_name: gaterdata-proxy
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro

  admin:
    container_name: gaterdata-admin
    build:
      context: .
      target: gaterdata-admin
    environment:
      - VIRTUAL_ROOT=/usr/share/nginx/html
      - VIRTUAL_HOST=admin.gaterdata.local
      - WEBROOT=/usr/share/nginx/html

  api:
    container_name: gaterdata-api
    build:
      context: .
      target: gaterdata-api
    environment:
      - VIRTUAL_ROOT=/usr/share/nginx/html
      - VIRTUAL_HOST=api.gaterdata.local
      - WEBROOT=/usr/share/nginx/html