version: '3.4'

services:
  
  proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro

  gaterdata:
    container_name: gaterdata
    image: richarvey/nginx-php-fpm
    environment:
      - VIRTUAL_ROOT=/usr/share/nginx/html
      - VIRTUAL_HOST=${GATERDATA_ADMIN},${GATERDATA_API}
      - WEBROOT=/usr/share/nginx/html
    volumes: 
      - .:/usr/share/nginx/html
      - ./.docker/admin.gaterdata.conf:/etc/nginx/vhost.d/${GATERDATA_ADMIN}
      - ./.docker/api.gaterdata.conf:/etc/nginx/vhost.d/${GATERDATA_API}