version: '3'
 
services:

  php:
    container_name: gaterdata_php
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./:/srv/www/api
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - network
 
  admin:
    container_name: gaterdata_admin
    image: nginx:1.16.1
    ports:
      - 80:80
    volumes:
      - ./:/srv/www/api
      - ./docker/nginx/admin.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - network
 
  sql:
    container_name: gaterdata_sql
    image: mariadb:10.4.7
    ports:
      - 3306:3306
    depends_on:
      - php
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - network

volumes:
  dbdata:
    driver: local

networks:
  network:
    driver: bridge