version: '3.7'

services:

  admin:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - ".:/usr/share/nginx/html"
    networks:
      - api_network
    container_name: "${APP_NAME}-nginx"
    
  php:
    build: ./docker/php
    image: php:fpm
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www/html"
    networks:
      - api_network
    container_name: "${APP_NAME}-php"

  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - api_network
    container_name: "${APP_NAME}-mysql"

networks:
  api_network:
    driver: bridge