version: '2'

services:

  web:
    image: nginx:latest
    links:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx/admin.conf:/etc/nginx/conf.d/000_default.conf
    volumes_from:
      - php

  php:
    build: .docker/nginx
    environment:
      - TYPO3_CONTEXT=Development/Docker
    # links:
    #   - db
      # - redis
    volumes:
      - .:/app

  # composer:
  #   image: composer:latest
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: install
  #   depends_on: [php]

  # db:
  #   image: mariadb:latest
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=secret
  #   volumes:
  #     - ./mysql:/var/lib/mysql

  # redis:
  #   image: redis:latest
