version: '2'

services:

  gaterdata-admin:
    image: nginx:latest
    container_name: gaterdata-admin
    environment:
      VIRTUAL_HOST: ${DOMAIN_ADMIN}
      VIRTUAL_PORT: 80
    volumes:
      - .:/app
      - .docker/vhost.d/admin.gaterdata.conf:/etc/nginx/vhost.d/${DOMAIN_ADMIN}:ro
    links:
      - php
      
  php:
    image: php:7-fpm

networks:
  default:
    external:
      name: nginx-proxy