# Example settings file.
#
# @package   ApiOpenStudio
# @license   This Source Code Form is subject to the terms of the ApiOpenStudio Public License.
#            If a copy of the license was not distributed with this file,
#            You can obtain one at https://www.apiopenstudio.com/license/.
# @author    john89 (https://gitlab.com/john89)
# @copyright 2020-2030 Naala Pty Ltd
# @link      https://www.apiopenstudio.com

debug:
  formatters:
    default:
      format: null
      date_format: null
      allow_inline_line_breaks: false
      ignore_empty_context_and_extra: true
  handlers:
    api_log_file:
      class: StreamHandler
      formatter: default
      level: DEBUG
      stream: /var/log/api.log
    db_log_file:
      class: StreamHandler
      formatter: default
      level: DEBUG
      stream: /var/log/db.log
  #    fire_php:
  #      class: FirePHPHandler
  #      formatter: default
  #    chrome_php:
  #      class: ChromePHPHandler
  #      formatter: default
  #    syslog:
  #      class: SyslogHandler
  #      ident: ApiOpenStudio
  #      facility: local6
  #      level: DEBUG
  #      formatter: default
  #    error_log:
  #      class: ErrorLogHandler
  #      formatter: default
  #    processor:
  #      class: ProcessHandler
  #      command: '/usr/bin/php /var/www/monolog/someScript.php'
  #      level: DEBUG
  #      formatter: default
  #    mongo_db:
  #      class: MongoDBHandler
  #      mongodb: client
  #      collection: logs
  #      level: DEBUG
  #      formatter: default
  loggers:
    api:
      handlers:
        - api_log_file
    db:
      handlers:
        - db_log_file

db:
  definition_path: "includes/db/dbDefinition.yaml"
  driver: mysqli
  host: apiopenstudio-db
  root_password: apiopenstudio
  username: apiopenstudio
  password: apiopenstudio
  database: apiopenstudio
  options:
    debug: false
  charset: utf8
  collation: utf8_unicode_ci

api:
  protocols:
    - https
  base_path: "/var/www/html/api/"
  url: "api.apiopenstudio.local"
  cache: false
  default_format: json
  wrap_json_in_response_object: true
  core_account: apiopenstudio
  core_application: core
  core_resource_lock: false
  dir_public: "public/"
  dir_resources: "includes/resources/"
  dir_uploads: "~/Downloads/"
  dir_tmp: "/tmp/"
  jwt_private_key: "/var/www/html/api/jwt.key"
  jwt_public_key: "/var/www/html/api/jwt.key.pub"
  jwt_alg_type: "Rsa"
  jwt_alg: "Sha256"
  jwt_life: "+1 hour"
  jwt_issuer: "api.apiopenstudio.local"
  jwt_permitted_for: "api.apiopenstudio.local"
  openapi_version: "3.0.3"
  openapi_directory: "includes/openapiSchema"

email:
  from: "Admin <admin@example.com>"
  reply_to: "Contact <contact@example.com>"
  dsn: "smtp://USERNAME:PASSWORD@DOMAIN:PORT"
