# Example settings file.
#
# @package   ApiOpenStudio
# @license   This Source Code Form is subject to the terms of the ApiOpenStudio Public License.
#            If a copy of the license was not distributed with this file,
#            You can obtain one at https://www.apiopenstudio.com/license/.
# @author    john89 (https://gitlab.com/john89)
# @copyright 2020-2030 Naala Pty Ltd
# @link      https://www.apiopenstudio.com

debug:
  formatters:
    api_open_studio:
      format: "%datetime%-%channel%.%level_name% - %message%\n"
  handlers:
    console:
      class: Monolog\Handler\StreamHandler
      level: DEBUG
      formatter: api_open_studio
      processors: [memory_processor]
      bubble: true
      stream: php://stdout
    api_file_handler:
      class: Monolog\Handler\StreamHandler
      level: NOTICE
      formatter: api_open_studio
      bubble: true
      stream: /var/www/html/logs/api/error.log
    db_file_handler:
      class: Monolog\Handler\StreamHandler
      level: NOTICE
      formatter: api_open_studio
      bubble: true
      stream: /var/www/html/logs/db/error.log
  processors:
    web_processor:
      class: Monolog\Processor\WebProcessor
    memory_processor:
      class: Monolog\Processor\MemoryUsageProcessor
  loggers:
    api:
      handlers: [api_file_handler]
      processors: [web_processor]
    db:
      handlers: [db_file_handler]
      processors: [web_processor]

db:
  definition_path: "includes/db/dbDefinition.yaml"
  driver: mysqli
  host: apiopenstudio-db
  root_password: apiopenstudio
  username: apiopenstudio
  password: apiopenstudio
  database: apiopenstudio
  options:
    debug: false
  charset: utf8
  collation: utf8_unicode_ci

api:
  protocols:
    - https
  base_path: "/var/www/html/api/"
  url: "api.apiopenstudio.local"
  cache: false
  default_format: json
  core_account: apiopenstudio
  core_application: core
  core_resource_lock: false
  dir_public: "public/"
  dir_resources: "includes/resources/"
  dir_uploads: "uploads/"
  dir_tmp: "/tmp/"
  jwt_private_key: "/var/www/html/api/jwtRS256.key"
  jwt_public_key: "/var/www/html/api/jwtRS256.key.pub"
  jwt_alg_type: "Rsa"
  jwt_alg: "Sha256"
  jwt_life: "+1 hour"
  jwt_issuer: "api.apiopenstudio.local"
  jwt_permitted_for: "api.apiopenstudio.local"

email:
  host: apiopenstudio-email
  username: "admin@apiopenstudio.com"
  password: "secret"
  from:
    email: "admin@apiopenstudio.com"
    name: "ApiOpenStudio admin"
