name: Application fetch

description: Fetch an application.

uri: application

method: get

ttl: 0

security:
  function: TokenSysAdmin
  id: 1
  token:
    function: varGet
    id: 2
    name: token

process:
  function: datagatorApplication
  id: 4
  applicationName:
    function: varGet
    id: 5
    name: applicationName
