name: Application delete

description: Delete an application.

uri: application

method: delete

ttl: 0

security:
  function: token_role
  id: application_delete_security
  token:
    function: bearer_token
    id: application_delete_token
  role: Administrator

process:
  function: application
  id: application_delete_process
  accountName:
    function: var_uri
    id: application_delete_account_name
    index: 0
  applicationName:
    function: var_uri
    id: application_delete_application_name
    index: 1
