name: Application create

description: Create an application.

uri: application

method: post

ttl: 0

security:
  function: TokenSysAdmin
  id: 1
  token:
    function: varPost
    id: 2
    name: token

process:
  function: datagatorApplication
  id: 4
  accountName:
    function: varPost
    id: 5
    name: accountName
  applicationName:
    function: varPost
    id: 7
    name: applicationName
