name: Application delete

description: Delete an application.

uri:
  noun: application
  verb: manage

method: delete

ttl: 0

security:
  function: TokenSysAdmin
  id: 1
  token:
    function: varGet
    id: 2
    name: token

process:
  function: datagatorApplication
  id: 3
  applicationName:
    function: varGet
    id: 5
    name: applicationName
