name: Application create

description: Create an application.

uri: application

method: post

appid: 2

ttl: 0

security:
  function: token_roles
  id: application_create_security
  token:
    function: bearer_token
    id: application_create_token
  roles:
    - Administrator
    - Account manager

process:
  function: application_create
  id: application_create_process
  accid:
    function: var_post
    id: application_create_accid
    key: accid
  name:
    function: var_post
    id: application_create_name
    key: name
