# Application create resource.
# @author john89
# @copyright 2020-2030 GaterData
# @license This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
#     If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
# @link https://gaterdata.com

name: Application create

description: Create an application.

uri: application

method: post

appid: 2

ttl: 0

security:
  function: token_roles
  id: application_create_security
  token:
    function: bearer_token
    id: application_create_security_token
  roles:
    - Administrator
    - Account manager

process:
  function: application_create
  id: application_create_process
  token:
    function: bearer_token
    id: account_create_token
  accid:
    function: var_post
    id: application_create_accid
    key: accid
  name:
    function: var_post
    id: application_create_name
    key: name
