# Application create resource.
#
# @package   Apiopenstudio\Resources
# @license   This Source Code Form is subject to the terms of the ApiOpenStudio Public License.
#            If a copy of the license was not distributed with this file,
#            You can obtain one at https://www.apiopenstudio.com/license/.
# @author    john89 (https://gitlab.com/john89)
# @copyright 2020-2030 Naala Pty Ltd
# @link      https://www.apiopenstudio.com

name: Application create

description: Create an application.

uri: application

method: post

appid: 1

ttl: 0

security:
  id: application_create_security
  processor: validate_token_roles
  validate_account: false
  validate_application: false
  roles:
    - Administrator
    - Account manager

process:
  processor: application_create
  id: application_create_process
  accid:
    processor: var_post
    id: application_create_accid
    expected_type: integer
    key: accid
  name:
    processor: var_post
    id: application_create_name
    expected_type: text
    key: name
