# Application update resource.
#
# @package   Apiopenstudio
# @license   This Source Code Form is subject to the terms of the ApiOpenStudio Public License.
#            If a copy of the license was not distributed with this file,
#            You can obtain one at https://www.apiopenstudio.com/license/.
# @author    john89 (https://gitlab.com/john89)
# @copyright 2020-2030 Naala Pty Ltd
# @link      https://www.apiopenstudio.com

name: Application update

description: Update an application.

uri: application

method: put

appid: 1

ttl: 0

security:
  id: application_update_security
  processor: validate_token_roles
  roles:
    - Administrator
    - Account manager

process:
  processor: application_update
  id: application_update_process
  appid:
    processor: var_uri
    id: application_update_appid
    index: 0
  accid:
    processor: var_uri
    id: application_update_accid
    index: 1
  name:
    processor: var_uri
    id: application_update_name
    index: 2
