name: Application update

description: Update an application.

uri: application

method: put

appid: 2

ttl: 0

security:
  function: token_roles
  id: application_update_security
  token:
    function: bearer_token
    id: application_update_token
  roles:
    - Administrator
    - Account manager

process:
  function: application_update
  id: application_update_process
  uid:
    function: field_value
    id: application_update_uid
    key_value: value
    field:
      function: var_field
      id: application_update_field_uid
      array:
        function: filter
        id: application_update_filter uid
        filter: uid
        inverse: true
        source:
          function: user_read
          id: application_update_user
          token:
            function: bearer_token
            id: application_update_uid_token
  appid:
    function: var_uri
    id: application_update_appid
    index: 0
  accid:
    function: var_uri
    id: application_update_accid
    index: 1
  name:
    function: var_uri
    id: application_update_name
    index: 2
