# Application read resource.
#
# @package   Apiopenstudio
# @license   This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
#            If a copy of the MPL was not distributed with this file,
#            You can obtain one at https://mozilla.org/MPL/2.0/.
# @author    john89 (https://gitlab.com/john89)
# @copyright 2020-2030 Naala Pty Ltd
# @link      https://www.apiopenstudio.com

name: Application read

description: Fetch a single or multiple applications.

uri: application

method: get

appid: 1

ttl: 0

security:
  processor: token_roles
  id: application_read_security
  token:
    processor: bearer_token
    id: application_read_security_bearer_token
  roles:
    - Administrator
    - Account manager
    - Application manager
    - Developer
  validate_account: false
  validate_application: false

process:
  processor: application_read
  id: application_read_process
  token:
    processor: bearer_token
    id: application_read_bearer_token
  accountId:
    processor: var_get
    id: application_read_account_id
    nullable: true
    key: account_id
  applicationId:
    processor: var_get
    id: application_read_application_id
    nullable: true
    key: application_id
  keyword:
    processor: var_get
    id: application_read_keyword
    nullable: true
    key: keyword
  orderBy:
    processor: var_get
    id: application_read_order_by
    nullable: true
    key: order_by
  direction:
    processor: var_get
    id: application_read_direction
    nullable: true
    key: direction
