name: Application create

description: Create an application.

uri: application

method: post

appid: 2

ttl: 0

security:
  function: token_roles
  id: application_create_security
  token:
    function: bearer_token
    id: application_create_token
  roles:
    - Administrator
    - Account manager

process:
  function: application_create
  id: application_create_process
  uid:
    function: field_value
    id: application_read_uid
    key_value: value
    field:
      function: var_field
      id: application_read_field_uid
      array:
        function: filter
        id: application_read_filter uid
        filter: uid
        inverse: true
        source:
          function: user_read
          id: application_read_user
          token:
            function: bearer_token
            id: application_read_uid_token
  accid:
    function: var_post
    id: application_create_accid
    key: accid
  name:
    function: var_post
    id: application_create_name
    key: name
