# Application delete resource.
#
# @package   Apiopenstudio
# @license   This Source Code Form is subject to the terms of the ApiOpenStudio Public License.
#            If a copy of the license was not distributed with this file,
#            You can obtain one at https://www.apiopenstudio.com/license/.
# @author    john89 (https://gitlab.com/john89)
# @copyright 2020-2030 Naala Pty Ltd
# @link      https://www.apiopenstudio.com

name: Application delete

description: Delete an application.

uri: application

method: delete

appid: 1

ttl: 0

security:
  id: application_delete_security
  processor: validate_token_roles
  validate_account: false
  validate_application: false
  roles:
    - Administrator
    - Account manager

process:
  processor: application_delete
  id: application_delete_process
  applicationId:
    processor: var_uri
    id: application_delete_application_id
    expected_type: integer
    index: 0
