name: Application read

description: Fetch a single or multiple applications.

uri: application

method: get

appid: 2

ttl: 0

security:
  function: token_roles
  id: application_read_security
  token:
    function: bearer_token
    id: application_read_bearer_token
  roles:
    - Administrator
    - Account manager
    - Application manager
    - Developer

process:
  function: application_read
  id: application_read_process
  accountIds:
    function: var_get
    id: application_read_account_ids
    nullable: true
    key: account_ids
  applicationNames:
    function: var_get
    id: application_read_application_names
    nullable: true
    key: application_names
  accountFilter:
    function: var_get
    id: application_read_account_filter
    nullable: true
    key: account_filter
  keyword:
    function: var_get
    id: application_read_keyword
    nullable: true
    key: keyword
  orderBy:
    function: var_get
    id: application_read_order_by
    nullable: true
    key: order_by
  direction:
    function: var_get
    id: application_read_direction
    nullable: true
    key: direction
