# Application read resource.
#
# @package   Apiopenstudio
# @license   This Source Code Form is subject to the terms of the ApiOpenStudio Public License.
#            If a copy of the license was not distributed with this file,
#            You can obtain one at https://www.apiopenstudio.com/license/.
# @author    john89 (https://gitlab.com/john89)
# @copyright 2020-2030 Naala Pty Ltd
# @link      https://www.apiopenstudio.com

name: Application read

description: Fetch a single or multiple applications.

uri: application

method: get

appid: 1

ttl: 0

security:
  id: application_read_security
  processor: validate_token

process:
  processor: application_read
  id: application_read_process
  accountId:
    processor: var_get
    id: application_read_account_id
    nullable: true
    key: account_id
  applicationId:
    processor: var_get
    id: application_read_application_id
    nullable: true
    key: application_id
  keyword:
    processor: var_get
    id: application_read_keyword
    nullable: true
    key: keyword
  orderBy:
    processor: var_get
    id: application_read_order_by
    nullable: true
    key: order_by
  direction:
    processor: var_get
    id: application_read_direction
    nullable: true
    key: direction
