name: Application delete

description: Delete an application.

uri: application

method: delete

appid: 2

ttl: 0

security:
  function: token_roles
  id: application_delete_security
  token:
    function: bearer_token
    id: application_delete_token
  roles:
    - Administrator
    - Account manager

process:
  function: application_delete
  id: application_delete_process
  uid:
    function: field_value
    id: application_delete_uid
    key_value: value
    field:
      function: var_field
      id: application_delete_field_uid
      array:
        function: filter
        id: application_delete_filter uid
        filter: uid
        inverse: true
        source:
          function: user_read
          id: application_delete_user
          token:
            function: bearer_token
            id: application_delete_uid_token
  applicationId:
    function: var_uri
    id: application_delete_application_id
    index: 0
