# Application create resource.
#
# @package   Apiopenstudio
# @license   This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
#            If a copy of the MPL was not distributed with this file,
#            You can obtain one at https://mozilla.org/MPL/2.0/.
# @author    john89 (https://gitlab.com/john89)
# @copyright 2020-2030 Naala Pty Ltd
# @link      https://www.apiopenstudio.com

name: Application create

description: Create an application.

uri: application

method: post

appid: 1

ttl: 0

security:
  processor: token_roles
  id: application_create_security
  token:
    processor: bearer_token
    id: application_create_security_token
  roles:
    - Administrator
    - Account manager

process:
  processor: application_create
  id: application_create_process
  token:
    processor: bearer_token
    id: account_create_token
  accid:
    processor: var_post
    id: application_create_accid
    key: accid
  name:
    processor: var_post
    id: application_create_name
    key: name
