# Application delete resource.
#
# @package   Apiopenstudio
# @license   This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
#            If a copy of the MPL was not distributed with this file,
#            You can obtain one at https://mozilla.org/MPL/2.0/.
# @author    john89 (https://gitlab.com/john89)
# @copyright 2020-2030 Naala Pty Ltd
# @link      https://www.apiopenstudio.com

name: Application delete

description: Delete an application.

uri: application

method: delete

appid: 1

ttl: 0

security:
  function: token_roles
  id: application_delete_security
  token:
    function: bearer_token
    id: application_delete_security_token
  roles:
    - Administrator
    - Account manager

process:
  function: application_delete
  id: application_delete_process
  token:
    function: bearer_token
    id: account_delete_token
  applicationId:
    function: var_uri
    id: application_delete_application_id
    index: 0
