# OpenApi read.
#
# @package   Apiopenstudio\Resources
# @license   This Source Code Form is subject to the terms of the ApiOpenStudio Public License.
#            If a copy of the license was not distributed with this file,
#            You can obtain one at https://www.apiopenstudio.com/license/.
# @author    john89 (https://gitlab.com/john89)
# @copyright 2020-2030 Naala Pty Ltd
# @link      https://www.apiopenstudio.com

name: OpenApi read

description: Fetch OpenApi documentation for an application and its resources, limited by user access rights.

uri: openapi

method: get

appid: 1

ttl: 0

security:
    processor: validate_token
    id: openapi_read_security

process:
    processor: openapi_read
    id: openapi_read_process
    appid:
        processor: var_get
        id: openapi_read_appid
        expected_type: integer
        key: appid
