# OpenApi default.
#
# @package   Apiopenstudio
# @license   This Source Code Form is subject to the terms of the ApiOpenStudio Public License.
#            If a copy of the license was not distributed with this file,
#            You can obtain one at https://www.apiopenstudio.com/license/.
# @author    john89 (https://gitlab.com/john89)
# @copyright 2020-2030 Naala Pty Ltd
# @link      https://www.apiopenstudio.com

name: OpenApi default

description: Generate default OpenApi documentation for an application and all its resources.

uri: openapi/default

method: post

appid: 1

ttl: 3600

security:
  processor: validate_token
  id: openapi_default_security

process:
  processor: openapi_default
  id: openapi_default_process
  appid:
    processor: var_uri
    id: openapi_default_appid
    index: 0
    expected_type: integer
